# Generated by Django 2.1.4 on 2019-03-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageclass',
            name='im_path',
        ),
        migrations.AddField(
            model_name='imageclass',
            name='im_photo',
            field=models.ImageField(default='', editable=False, upload_to='capture'),
        ),
    ]
