# Generated by Django 2.1.4 on 2019-03-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0002_auto_20190315_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaryClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('im_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='imageclass',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
