# Generated by Django 2.1.4 on 2019-03-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0003_auto_20190319_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GaryClass',
        ),
    ]
