# Generated by Django 2.1.4 on 2019-03-19 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0004_delete_garyclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageclass',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
