# Generated by Django 2.1.4 on 2019-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0009_auto_20190326_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='im_url',
            field=models.CharField(default='Noo', max_length=1000),
        ),
    ]
