# Generated by Django 2.1.4 on 2019-04-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0010_auto_20190326_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageclass',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='imageclass',
            name='im_url',
        ),
    ]
