# Generated by Django 2.1.4 on 2019-04-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0011_auto_20190401_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='im_photo',
            field=models.ImageField(default='', upload_to='capture/'),
        ),
    ]
