# Generated by Django 2.1.4 on 2019-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0012_auto_20190401_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='im_photo',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
