# Generated by Django 2.1.4 on 2019-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0013_auto_20190402_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='im_photo',
            field=models.ImageField(default='', upload_to='capture/'),
        ),
    ]
