# Generated by Django 2.1.4 on 2019-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0014_auto_20190402_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgClass',
        ),
        migrations.AlterField(
            model_name='imageclass',
            name='im_photo',
            field=models.ImageField(default='', upload_to='capture'),
        ),
    ]
