# Generated by Django 2.1.4 on 2019-04-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0020_auto_20190410_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='im_type',
            field=models.CharField(blank=True, choices=[('HD', 'human_detected'), ('FD', 'fire_detected')], default=' ', max_length=2, null=True),
        ),
    ]
