# Generated by Django 2.1.4 on 2019-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0021_auto_20190410_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='im_type',
            field=models.CharField(blank=True, choices=[('HD', 'Human Detected'), ('FD', 'Fire Detected')], default=' ', max_length=2, null=True),
        ),
    ]
