# Generated by Django 2.1.4 on 2019-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0022_auto_20190410_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNotPresentClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_person', models.CharField(max_length=100)),
                ('duration_specified', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
