# Generated by Django 2.1.4 on 2019-04-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0023_personnotpresentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='im_type',
            field=models.CharField(blank=True, choices=[('HD', 'Human Detected'), ('FD', 'Fire Detected'), ('PM', 'Person Missing')], default=' ', max_length=3, null=True),
        ),
    ]
