# Generated by Django 2.1.4 on 2019-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0024_auto_20190415_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFormForOperations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fire_checker', models.BooleanField()),
                ('fr_start_time', models.DateTimeField()),
                ('fr_stop_time', models.DateTimeField()),
                ('start_stop', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='PersonNotPresentClass',
        ),
    ]
