# Generated by Django 2.1.4 on 2019-04-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0025_auto_20190423_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputformforoperations',
            name='fr_stop_time',
        ),
        migrations.AddField(
            model_name='inputformforoperations',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputformforoperations',
            name='fr_end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inputformforoperations',
            name='hcnp_end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inputformforoperations',
            name='hcnp_start_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='inputformforoperations',
            name='hcp_end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inputformforoperations',
            name='hcp_start_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='inputformforoperations',
            name='human_checker_not_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputformforoperations',
            name='human_checker_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inputformforoperations',
            name='fire_checker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inputformforoperations',
            name='fr_start_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='inputformforoperations',
            name='start_stop',
            field=models.BooleanField(default=False),
        ),
    ]
