# Generated by Django 2.1.4 on 2019-04-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0026_auto_20190423_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputformforoperations',
            name='start_stop',
        ),
    ]
