# Generated by Django 2.1.4 on 2019-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_detection_api', '0027_remove_inputformforoperations_start_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputformforoperations',
            name='hcp_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
